Repository Win-ther/SpringbootGroupProject, pull requests merged in 2024-03, with the labels that each got.

#18 Add settings to application.properties
  src/main/resources/application.properties
Labels: enhancement

#15 1 user entity
  src/main/java/se/iths/SpringbootGroupProject/entities/User.java
Labels: enhancement

#26 Bugfix for pullrequest template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#20 5 add internationalization
  src/main/java/se/iths/SpringbootGroupProject/configurations/MessageConfig.java
  src/main/resources/application.properties
  src/main/resources/lang/messages.properties
  src/main/resources/lang/messages_en.properties
  src/main/resources/lang/messages_sv.properties
Labels: enhancement

#28 Add Message entity
  src/main/java/se/iths/SpringbootGroupProject/SpringbootGroupProjectApplication.java
  src/main/java/se/iths/SpringbootGroupProject/entities/Message.java
  src/main/java/se/iths/SpringbootGroupProject/entities/User.java
Labels: enhancement

#19 13 add ci pipeline and .dockerignore
  .dockerignore
  .github/workflows/pipeline.yml
  pom.xml
  src/test/java/se/iths/SpringbootGroupProject/SpringbootGroupProjectApplicationTests.java
Labels: devops

#27 Add spring-boot-starter-validation to pom.xml
  pom.xml
Labels: enhancement

#30 Create dependabot.yml
  .github/dependabot.yml
Labels: devops

#31 22 add sonarcloud to pipeline
  .github/workflows/pipeline.yml
  pom.xml
Labels: devops

#29 3 repositories for entities
  src/main/java/se/iths/SpringbootGroupProject/entities/Message.java
  src/main/java/se/iths/SpringbootGroupProject/entities/User.java
  src/main/java/se/iths/SpringbootGroupProject/repositories/MessageRepository.java
  src/main/java/se/iths/SpringbootGroupProject/repositories/UserRepository.java
Labels: enhancement

#35 Generated the V1 of our database schema using flyway.
  .jpb/jpb-settings.xml
  src/main/java/se/iths/SpringbootGroupProject/entities/User.java
  src/main/resources/db/migration/V1__.sql
Labels: enhancement

#36 4 service layer for repositories
  pom.xml
  src/main/java/se/iths/SpringbootGroupProject/SpringbootGroupProjectApplication.java
  src/main/java/se/iths/SpringbootGroupProject/configurations/CachingConfig.java
  src/main/java/se/iths/SpringbootGroupProject/controllers/GuestController.java
  src/main/java/se/iths/SpringbootGroupProject/services/MessageService.java
  src/main/java/se/iths/SpringbootGroupProject/services/UserService.java
Labels: enhancement

#38 Refactor se.iths.SpringbootGroupProject to lowercase
  .jpb/jpb-settings.xml
  src/main/java/se/iths/springbootgroupproject/SpringbootGroupProjectApplication.java
  src/main/java/se/iths/springbootgroupproject/configurations/CachingConfig.java
  src/main/java/se/iths/springbootgroupproject/configurations/MessageConfig.java
  src/main/java/se/iths/springbootgroupproject/controllers/GuestController.java
  src/main/java/se/iths/springbootgroupproject/dto/PublicMessageAndUsername.java
  src/main/java/se/iths/springbootgroupproject/entities/Message.java
  src/main/java/se/iths/springbootgroupproject/entities/User.java
  src/main/java/se/iths/springbootgroupproject/repositories/MessageRepository.java
  src/main/java/se/iths/springbootgroupproject/repositories/UserRepository.java
  src/main/java/se/iths/springbootgroupproject/services/MessageService.java
  src/main/java/se/iths/springbootgroupproject/services/UserService.java
  src/test/java/se/iths/springbootgroupproject/TestSpringbootGroupProjectApplication.java
Labels: bug, minor

#43 40 modifying annotation in repository should only return void or int / small refactor and update
  src/main/java/se/iths/springbootgroupproject/controllers/GuestController.java
  src/main/java/se/iths/springbootgroupproject/dto/PublicMessageAndUsername.java
  src/main/java/se/iths/springbootgroupproject/entities/Message.java
  src/main/java/se/iths/springbootgroupproject/repositories/MessageRepository.java
  src/main/java/se/iths/springbootgroupproject/repositories/UserRepository.java
  src/main/java/se/iths/springbootgroupproject/services/MessageService.java
  src/main/resources/application.properties
Labels: bug, enhancement

#47 Add LICENSE
  LICENSE
Labels: documentation

#44 Add WebController and /web/welcome site.
  .jpb/jpb-settings.xml
  src/main/java/se/iths/springbootgroupproject/SpringbootGroupProjectApplication.java
  src/main/java/se/iths/springbootgroupproject/controllers/WebController.java
  src/main/java/se/iths/springbootgroupproject/repositories/MessageRepository.java
  src/main/java/se/iths/springbootgroupproject/repositories/UserRepository.java
  src/main/java/se/iths/springbootgroupproject/services/MessageService.java
  src/main/java/se/iths/springbootgroupproject/services/UserService.java
  src/main/resources/application.properties
  src/main/resources/lang/messages.properties
  src/main/resources/lang/messages_en.properties
  src/main/resources/lang/messages_sv.properties
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/templates/welcome.html
Labels: enhancement, project criteria

#52 Add page to view all messages
  src/main/java/se/iths/springbootgroupproject/configurations/CachingConfig.java
  src/main/java/se/iths/springbootgroupproject/controllers/GuestController.java
  src/main/java/se/iths/springbootgroupproject/controllers/WebController.java
  src/main/java/se/iths/springbootgroupproject/dto/MessageAndUsername.java
  src/main/java/se/iths/springbootgroupproject/dto/PublicMessageAndUsername.java
  src/main/java/se/iths/springbootgroupproject/repositories/MessageRepository.java
  src/main/java/se/iths/springbootgroupproject/services/MessageService.java
  src/main/resources/lang/messages.properties
  src/main/resources/lang/messages_en.properties
  src/main/resources/lang/messages_sv.properties
  src/main/resources/static/styles.css
  src/main/resources/templates/messages.html
Labels: enhancement, project criteria
